# Generated by Django 6.0.3 on 2026-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_address_profile_city_profile_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
