# Generated by Django 6.0.3 on 2026-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_dob_alter_profile_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INFORMATICS", "Informatics"),
                    ("ENGINEER", "Engineer"),
                    ("DOCTOR", "Doctor"),
                    ("DESIGN", "Design"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
