# Generated by Django 6.0.3 on 2026-09-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_profession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
