services:
  daphne:
    build: .
    working_dir: /code/symox/
    command: ["../wait-for-it.sh", "db:5432", "--",
              "daphne", "-b", "0.0.0.0", "-p", "9001",
              "symox.asgi:application"]
    restart: always
    volumes:
      - .:/code
    
    environment:
      - DJANGO_SETTINGS_MODULE=symox.settings.prod
      - POSTGRES_DB=canary
      - POSTGRES_USER=canary
      - POSTGRES_PASSWORD=canary=value

    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=canary
      - POSTGRES_USER=canary
      - POSTGRES_PASSWORD=canary

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./data/cache:/data
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
      "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini",
      
      ]

    restart: always
    volumes:
      - ./code

    ports:
      - "8000"

    environment:
      - DJANGO_SETTINGS_MODULE=symox.settings.prod
      - DB_NAME=canary
      - DB_USER=canary
      - DB_PASSWORD=canary

    depends_on:
      - db
      - cache

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code

    ports:
      - "80:80"
      - "443:443"