# Generated by Django 6.0.3 on 2026-08-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Subject",
            new_name="subject",
        ),
    ]
