# Generated by Django 6.0.3 on 2026-09-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0005_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="module",
            name="course",
        ),
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="text",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="video",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Text",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
