# Generated by Django 6.0.3 on 2026-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencypair",
            name="display_precision",
            field=models.IntegerField(default=5, max_length=5),
        ),
    ]
