# Generated by Django 6.0.3 on 2026-09-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_currencypair_display_precision"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candle",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="candle",
            name="market_cand_pair_id_aa60ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="candle",
            name="market_cand_timefra_b0fe30_idx",
        ),
        migrations.DeleteModel(
            name="Candle",
        ),
        migrations.DeleteModel(
            name="CurrencyPair",
        ),
    ]
