# Generated by Django 6.0.3 on 2026-09-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0003_alter_candle_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=30)),
                ("pip_location", models.IntegerField(default=-4)),
                ("display_precision", models.IntegerField(default=5, max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeframe", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=15)),
                ("high", models.DecimalField(decimal_places=8, max_digits=15)),
                ("low", models.DecimalField(decimal_places=8, max_digits=15)),
                ("close", models.DecimalField(decimal_places=8, max_digits=15)),
                ("volume", models.PositiveIntegerField()),
                ("complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candles",
                        to="market.currencypair",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pair", "timestamp"],
                        name="market_cand_pair_id_aa60ae_idx",
                    ),
                    models.Index(
                        fields=["timeframe"], name="market_cand_timefra_b0fe30_idx"
                    ),
                ],
                "unique_together": {("pair", "timeframe", "timestamp")},
            },
        ),
    ]
