# Generated by Django 6.0.3 on 2026-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("YES", "is_vailable"), ("NO", "unavailable")],
                default="NO",
                max_length=10,
            ),
        ),
    ]
