# Generated by Django 6.0.3 on 2026-07-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_is_available_alter_product_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.CharField(
                choices=[("YES", "is_vailable"), ("NO", "unavailable")],
                default="NO",
                max_length=10,
            ),
        ),
    ]
